version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: DBMS
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data           # Persistent data
      - ./postgresql/init:/docker-entrypoint-initdb.d        # Init scripts (SQL or .sh)
      - ./postgresql/backups:/backups                        # Backup folder
    restart: unless-stopped
